export enum DateFormat {
  EXHIBITION_TIME = 'HH:mm:ss',
  EXHIBITION_TIME_MILLIES = 'HH:mm:ss.SS',
  LOCAL_DATE = 'YYYY-MM-DD',
  LOCAL_DATE_TIME = 'YYYY-MM-DDTHH:mm:ss.SSSSSS',
  EXHIBITION_DATE = 'DD/MM/YYYY',
  EXHIBITION_DATE_TWO_DIGITS = 'DD/MM/YY',
  EXHIBITION_DATE_TIME = 'DD/MM/YYYY HH:mm:ss',
  EXHIBITION_DATE_TIME_TWO_DIGITS = 'DD/MM/YY HH:mm:ss',
}
